# Generated by Django 4.2.4 on 2024-03-27 10:56

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=100)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('course_des', tinymce.models.HTMLField(blank=True, default=None, null=True)),
                ('skills', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('review', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('course_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advance', 'Advance')], default='Beginner', max_length=50)),
                ('course_duration', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('course_image', models.ImageField(default='course/courses-1.jpg', null=True, upload_to='corse/')),
                ('course_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_title', unique=True)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companys.company')),
                ('skills_req', models.ManyToManyField(to='uploads.skil')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(help_text='Enter your cover letter here.')),
                ('available', models.BooleanField(default=False, help_text='Check if you are available for this internship.')),
                ('resume', models.FileField(blank=True, help_text='Upload your resume.', upload_to='documents/')),
                ('is_accepted', models.BooleanField(default=False, help_text='Check if your application is accepted.')),
                ('is_rejected', models.BooleanField(default=False, help_text='Check if your application is rejected.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applicant', to='course.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Applicant',
                'verbose_name_plural': 'Course Applicant',
                'unique_together': {('student', 'course')},
            },
        ),
    ]
