# Generated by Django 4.2.4 on 2023-10-16 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursera_Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('skills', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('review', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('course_for', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 3, 13, 70807, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Indeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('company', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('locations', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('salary', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('posted_at', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('links', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('about_text', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 3, 13, 68274, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='RelatedQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('snippet', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('link', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('displayedLink', models.URLField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('salary', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('top_comp_sal', models.JSONField(blank=True, default=None, null=True)),
                ('top_city_sal', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 3, 13, 70457, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeJobResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('link', models.URLField(blank=True, default=None, max_length=400, null=True)),
                ('displayedLink', models.URLField(blank=True, default=None, max_length=400, null=True)),
                ('source', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('snippet', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('snippetHighlitedWords', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indeed_job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('company', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('locations', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('salary', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('posted_at', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('links', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('about_text', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 3, 13, 69369, tzinfo=datetime.timezone.utc))),
                ('skill', models.ManyToManyField(blank=True, default=None, null=True, to='uploads.skil')),
            ],
        ),
    ]
