# Generated by Django 4.2.4 on 2023-10-16 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursera_courses',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 14, 1, 739408, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indeed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 14, 1, 736626, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indeed_job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 14, 1, 737842, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 14, 1, 739042, tzinfo=datetime.timezone.utc)),
        ),
    ]
