# Generated by Django 4.2.4 on 2023-10-16 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_data', '0002_alter_coursera_courses_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('skills', models.CharField(blank=True, default=None, max_length=5000, null=True)),
                ('review', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('course_for', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 15, 50, 775918, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Coursera_Courses',
        ),
        migrations.AlterField(
            model_name='indeed',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 15, 50, 773447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='indeed_job',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 15, 50, 774399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 16, 7, 15, 50, 775545, tzinfo=datetime.timezone.utc)),
        ),
    ]
