# Generated by Django 4.2.4 on 2024-03-27 10:56

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Internship', 'Internship')], default=None, max_length=50, null=True)),
                ('exp_required', models.CharField(max_length=100)),
                ('job_des', tinymce.models.HTMLField(blank=True, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the minimum salary for this job (e.g., 50000.00)', max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Enter the maximum salary for this job (e.g., 80000.00)', max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('location', models.CharField(max_length=250)),
                ('area', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('pincode', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,6}$')])),
                ('recruitment_timeline', models.CharField(choices=[('1 to 3 days', '1 to 3 days'), ('3 to 7 days', '3 to 7 days'), ('1 to 2 weeks', '1 to 2 weeks'), ('2 to 4 weeks', '2 to 4 weeks'), ('More than 4 weeks', 'More than 4 weeks')], default=None, max_length=250)),
                ('company_desc', tinymce.models.HTMLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_image', models.ImageField(default='job/jobs-1.jpg', upload_to='job/')),
                ('job_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='get_full_slug', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.city')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='companys.company')),
                ('skills_req', models.ManyToManyField(to='uploads.skil')),
                ('sub_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='job.subcategory')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applicants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Applicant',
                'verbose_name_plural': 'Job Applicant',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
